# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datamhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import pymysql
from PyQt5.QtWidgets import *

from datamhs import *


class datamhs(QWidget):
    def __init__(self):
        super().__init__()
        self.datamhs = Ui_datamhs()
        self.datamhs.setupUi(self)
        # self.datamhs.Tambah.clicked.connect(self.submit)

    def submit(self):
        nim = self.datamhs.Nim.text()
        nama = self.datamhs.Nama.text()
        jurusan = self.datamhs.Jurusan.text()
        no = self.datamhs.noTelp.text()
        insert = (nim, nama, jurusan, no)
        print(insert)
        if self.datamhs.Nim.text() and self.datamhs.Nama.text() and self.datamhs.Jurusan.text() and self.datamhs.noTelp.text():
            con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO mhs(nim, nama, jurusan, no)" + "VALUES" + str(insert)
            data = cur.execute(sql)
            Ui_MainWindow.messagebox(Ui_MainWindow, "SUKSES", "Data Berhasil di Submit")
        else:
            Ui_MainWindow.messagebox(Ui_MainWindow, "GAGAL" "Mohon lengkapi form ")


class Ui_datamhs(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")


class Ui_MainWindow(object):
    def openWindow(self):
        print("halo")
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        self.koneksi()
        MainWindow.setObjectName("MainWindow")

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 270, 271, 241))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Gambar/student.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 90, 601, 156))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtNim = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtNim.setFont(font)
        self.txtNim.setObjectName("txtNim")
        self.gridLayout.addWidget(self.txtNim, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtNama = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtNama.setFont(font)
        self.txtNama.setObjectName("txtNama")
        self.gridLayout.addWidget(self.txtNama, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.txtNo = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtNo.setFont(font)
        self.txtNo.setObjectName("txtNo")
        self.gridLayout.addWidget(self.txtNo, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtJurusan = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtJurusan.setFont(font)
        self.txtJurusan.setObjectName("txtJurusan")
        self.gridLayout.addWidget(self.txtJurusan, 2, 1, 1, 1)
        self.btnSubmit = QtWidgets.QPushButton(self.tab)
        self.btnSubmit.setGeometry(QtCore.QRect(580, 270, 111, 31))
        self.btnSubmit.setObjectName("btnSubmit")
        self.btnSubmit.clicked.connect(self.submit)

        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(280, 20, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(40, 300, 261, 211))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Gambar/admin.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(120, 110, 551, 101))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtUname = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtUname.setFont(font)
        self.txtUname.setObjectName("txtUname")
        self.gridLayout_2.addWidget(self.txtUname, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.txtPass = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPass.setFont(font)
        self.txtPass.setObjectName("txtPass")
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.Password)

        self.gridLayout_2.addWidget(self.txtPass, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(320, 40, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btnLogin = QtWidgets.QPushButton(self.tab_2)
        self.btnLogin.setGeometry(QtCore.QRect(570, 230, 101, 31))
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin.clicked.connect(self.login)

        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Nama"))
        self.label_5.setText(_translate("MainWindow", "No.Telp"))
        self.label_4.setText(_translate("MainWindow", "Jurusan"))
        self.label_2.setText(_translate("MainWindow", "NIM"))
        self.btnSubmit.setText(_translate("MainWindow", "Submit"))
        self.label_6.setText(_translate("MainWindow", "Form Mahasiswa"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Form"))
        self.label_8.setText(_translate("MainWindow", "Password"))
        self.label_11.setText(_translate("MainWindow", "Username"))
        self.label_9.setText(_translate("MainWindow", "login Admin"))
        self.btnLogin.setText(_translate("MainWindow", "LOGIN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Admin"))

    def koneksi(self):
        con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if (cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def submit(self):
        nim = self.txtNim.text()
        nama = self.txtNama.text()
        jurusan = self.txtJurusan.text()
        no = self.txtNo.text()
        insert = (nim, nama, jurusan, no)
        print(insert)
        if self.txtNim.text() and self.txtNama.text() and self.txtJurusan.text() and self.txtNo.text():
            con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO mhs(nim, nama, jurusan, no)" + "VALUES" + str(insert)
            data = cur.execute(sql)
            self.messagebox("SUKSES", "Data Berhasil di Submit")
        else:
            self.messagebox("GAGAL", "Mohon lengkapi form ")

    def login(self):
        uname = self.txtUname.text()
        pw = self.txtPass.text()
        con = pymysql.connect(db='db_mhs', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "SELECT * from admin where uname=%s and pw=%s"
        data = cur.execute(sql, (uname, pw))
        if (len(cur.fetchall()) > 0):
            print("benar")
            self.openWindow()
            # self.form = datamhs()
            # self.form.show()
        else:
            self.messagebox("GAGAL", "Username atau Password Salah ! ")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
