# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TugasGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(18)

        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 480, 531, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Nim = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Nim.setFont(font)
        self.Nim.setObjectName("Nim")
        self.gridLayout.addWidget(self.Nim, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.Nama = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Nama.setFont(font)
        self.Nama.setObjectName("Nama")
        self.gridLayout.addWidget(self.Nama, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.Jurusan = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Jurusan.setFont(font)
        self.Jurusan.setObjectName("Jurusan")
        self.gridLayout.addWidget(self.Jurusan, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.noTelp = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.noTelp.setFont(font)
        self.noTelp.setObjectName("noTelp")
        self.gridLayout.addWidget(self.noTelp, 3, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 630, 395, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")

        # Fungsi Button Tambah
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Tambah = QtWidgets.QPushButton(self.layoutWidget1)
        self.Tambah.setObjectName("Tambah")
        self.Tambah.clicked.connect(self.addButtonClick)

        # Fungsi Button Edit
        self.horizontalLayout.addWidget(self.Tambah)
        self.Edit = QtWidgets.QPushButton(self.layoutWidget1)
        self.Edit.setObjectName("Edit")
        self.horizontalLayout.addWidget(self.Edit)

        # Fungsi Button Clear
        self.Clear = QtWidgets.QPushButton(self.layoutWidget1)
        self.Clear.setObjectName("Clear")
        self.Clear.clicked.connect(self.Nim.clear)
        self.Clear.clicked.connect(self.Nama.clear)
        self.Clear.clicked.connect(self.Jurusan.clear)
        self.Clear.clicked.connect(self.noTelp.clear)

        # Fungsi Button Hapus
        self.horizontalLayout.addWidget(self.Clear)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(70, 90, 531, 371))
        self.listWidget.setObjectName("listWidget")
        self.pushButton.clicked.connect(self.deleteButtonClick)

        self.listWidget.raise_()
        self.label.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Data Mahasiswa"))
        self.label_2.setText(_translate("MainWindow", "NIM"))
        self.label_3.setText(_translate("MainWindow", "Nama"))
        self.label_4.setText(_translate("MainWindow", "Jurusan"))
        self.label_5.setText(_translate("MainWindow", "No.Telp"))
        self.Tambah.setText(_translate("MainWindow", "TAMBAH"))
        self.Edit.setText(_translate("MainWindow", "EDIT"))
        self.Clear.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton.setText(_translate("MainWindow", "HAPUS"))

    def addButtonClick(self):
        self.listWidget.addItem(
           '"'+ self.Nim.text()  + '", "' + 
           self.Nama.text() + '", "' +
           self.Jurusan.text()  + '", "' +
           self.noTelp.text() + '"')

    def deleteButtonClick(self):
        row = self.listWidget.currentRow()
        if row >= 0:
            self.listWidget.takeItem(row)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
